---
title: "Problem Set 2 Solutions"
author: "Harris Goodman"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

> 1.  Write your name and surname in bold font, with your Name ONLY in
>     italics.

#### **Answer:**

***Harris* Goodman**

> 2.  Print your student number and what year you are in on different
>     lines.

#### **Answer:**

2101274

3

> 3.  Briefly state, in italics, why you are doing this Data Science
>     Module

#### **Answer:**

*I really enjoy using computational methods to solve problems using data and I am keen to learn and utilise the basic techniques of data science.*

> 4.  Make an unordered list of at least 3 things you have learned in
>     this module.

    Answer Below

> 5.  Create a table showing the 1st 5 stages of the John Rollins
>     General Data Science Methodology and the quetions associate with
>     them.

    Answer Below

> 6.  Create an ordered list of at least 3 other Data Science
>     methodologies.

    Answer Below

> 7.  Provide and ordered list the weaknesses of the CRISP-DM
>     methodology and how to address them

    Answer Below

> 8.  Download and include a University of Warwick Logo in your
>     document.

    Answer Below

> 9.  Write and execute a code to randomly generate 10 numbers from a
>     normal distribution with mean 12 and standard deviation 3.

    Answer Below

> 10. Write and execute a code to calculate the mean of 12 random
>     numbers generated from the intervalof integes from 5 to 25.

    Answer Below

> 11. Write and execute a code to create a scatter plot containing 12
>     points whose coordinates were randomly geenrated in the interval 5
>     to 25. Provide a title for the figure, label the x and y axis.

    Answer Below

> 12. Write and execute a code to create a function to calculate
>     standard error. Then, calculate the standard error of a set of 15
>     randomly generated numbers from a normal distribution with mean 12
>     and standard deviation 3.

    Answer Below

> 13. Given that BMI=kg/m2, where kg is the person’s weight in kilograms
>     and m2is height in meters squared, write and execute a code to
>     create a function that calculates the BMI of who weighs 85kg and
>     is 1.9m tall.

    Answer Below
